version: '3'

services:
  history-database:
    image: postgres:latest
    container_name: historydb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB:       "historydb"
      
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  redisserver:
    image: redis:alpine
    ports:
      - "6379:6379"
        
        
#  config-server:
#    image: config/config-service:0.0.1-SNAPSHOT
#    ports:
#       - "8071:8071"
#    container_name: config-server   
#    environment:
#      CONFIG_URL: http://config-server:8071
#      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
#    build: .
#    networks:
#      - servicenet
#
#  tourserver:
#
#    build: .
#    container_name: tourserver
#    restart: on-failure
#    networks:
#      - servicenet
#    image: exams/exam-service:0.0.1-SNAPSHOT
#    ports:
#       - "8080:8080"
#
#
#
#networks:
#  servicenet:
